// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/audit-requests": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Lists audit requests, optionally narrowed to one cluster.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit-requests"
                ],
                "summary": "List audit requests",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Restrict to requests for this cluster ID",
                        "name": "cluster_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/internal_server_http.auditRequestDTO"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "invalid cluster_id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "missing or invalid admin token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Creates a pending request to audit a cluster. Approving it later (PATCH with status=approved) triggers the configured pipeline.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit-requests"
                ],
                "summary": "Create an audit request",
                "parameters": [
                    {
                        "description": "Audit request to create",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.auditRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.auditRequestDTO"
                        }
                    },
                    "400": {
                        "description": "invalid request body / invalid clusterId / missing reason",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "missing or invalid admin token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/audit-requests/{id}": {
            "patch": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Transitions an audit request's status, typically pending -\u003e approved (which triggers the configured pipeline and moves it to running) or pending -\u003e rejected.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit-requests"
                ],
                "summary": "Update an audit request's status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Audit request ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New status",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.patchAuditRequestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.auditRequestDTO"
                        }
                    },
                    "400": {
                        "description": "invalid id / invalid request body / missing status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "missing or invalid admin token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "no such audit request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "triggering scan failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/automation-rules": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Lists every automation rule.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "automation-rules"
                ],
                "summary": "List automation rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/internal_server_http.automationRuleDTO"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "missing or invalid admin token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Creates a rule that fires an action (e.g. notify/file-jira) when its trigger matches a finding during evaluation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "automation-rules"
                ],
                "summary": "Create an automation rule",
                "parameters": [
                    {
                        "description": "Automation rule to create",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.automationRuleDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.automationRuleDTO"
                        }
                    },
                    "400": {
                        "description": "invalid request body / missing name or action.type",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "missing or invalid admin token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/automation-rules/evaluate": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Evaluates every enabled automation rule against current findings immediately, instead of waiting for the periodic ticker. Useful to demo automation without waiting for a timer.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "automation-rules"
                ],
                "summary": "Run one automation evaluation pass",
                "responses": {
                    "200": {
                        "description": "results",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/internal_server_http.automationEvaluationResultDTO"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "missing or invalid admin token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "automation runner not configured / evaluation failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/automation-rules/{id}": {
            "delete": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Deletes one automation rule by ID.",
                "tags": [
                    "automation-rules"
                ],
                "summary": "Delete an automation rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Automation rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "deleted"
                    },
                    "400": {
                        "description": "invalid id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "missing or invalid admin token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "no such automation rule",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Replaces the name/enabled/trigger/action of an existing automation rule. ID and createdAt are preserved from the existing record.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "automation-rules"
                ],
                "summary": "Update an automation rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Automation rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New rule content",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.automationRuleDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.automationRuleDTO"
                        }
                    },
                    "400": {
                        "description": "invalid id / invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "missing or invalid admin token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "no such automation rule",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/clusters": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Registers a new cluster and mints a bearer token for it. The token is only ever returned in this response — store it, it can't be recovered later.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "Register a cluster",
                "parameters": [
                    {
                        "description": "Cluster to register",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.registerClusterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.registerClusterResponse"
                        }
                    },
                    "400": {
                        "description": "missing name",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "missing or invalid admin token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "a cluster with this name already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/exclusion-rules": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Lists exclusion rules, optionally narrowed to one cluster (rules with no clusterId apply to every cluster).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exclusion-rules"
                ],
                "summary": "List exclusion rules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Restrict to rules for this cluster ID",
                        "name": "cluster_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/internal_server_http.exclusionRuleDTO"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "invalid cluster_id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "missing or invalid admin token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Creates a rule that suppresses matching findings, org-wide or for one cluster (clusterId).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exclusion-rules"
                ],
                "summary": "Create an exclusion rule",
                "parameters": [
                    {
                        "description": "Exclusion rule to create",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.exclusionRuleDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.exclusionRuleDTO"
                        }
                    },
                    "400": {
                        "description": "invalid request body / missing reason / invalid clusterId",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "missing or invalid admin token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/exclusion-rules/{id}": {
            "delete": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Deletes one exclusion rule by ID.",
                "tags": [
                    "exclusion-rules"
                ],
                "summary": "Delete an exclusion rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Exclusion rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "deleted"
                    },
                    "400": {
                        "description": "invalid id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "missing or invalid admin token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "no such exclusion rule",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ingest/native": {
            "post": {
                "security": [
                    {
                        "ClusterAuth": []
                    }
                ],
                "description": "Ingests a kubectl-audit native findings.json body for the cluster identified by the bearer token. May produce more than one Scan if the payload batches multiple sources.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "Ingest a native findings.json scan",
                "parameters": [
                    {
                        "description": "findings.json payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.ingestResponse"
                        }
                    },
                    "400": {
                        "description": "invalid payload",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "missing or invalid bearer token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ingest/openreports": {
            "post": {
                "security": [
                    {
                        "ClusterAuth": []
                    }
                ],
                "description": "Ingests an openreports.io/v1alpha1 Report or ClusterReport JSON body for the cluster identified by the bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "Ingest an OpenReports scan",
                "parameters": [
                    {
                        "description": "OpenReports Report/ClusterReport payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.ingestResponse"
                        }
                    },
                    "400": {
                        "description": "invalid payload",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "missing or invalid bearer token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/knowledge-base/{policyId}": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Returns the centralized knowledge base entry for one policy ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "knowledge-base"
                ],
                "summary": "Get a knowledge base entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy ID",
                        "name": "policyId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.knowledgeBaseEntryDTO"
                        }
                    },
                    "401": {
                        "description": "missing or invalid admin token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "no knowledge base entry for this policy id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Upserts the centralized knowledge base entry for one policy ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "knowledge-base"
                ],
                "summary": "Create or replace a knowledge base entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy ID",
                        "name": "policyId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Entry content",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.knowledgeBaseEntryDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.knowledgeBaseEntryDTO"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "missing or invalid admin token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/triage": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Returns every finding for one cluster merged with its triage state (status defaults to \"new\" when no triage entry exists yet).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "triage"
                ],
                "summary": "Get the merged findings+triage view",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster ID",
                        "name": "cluster_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Restrict to one ingest source, e.g. native or openreports",
                        "name": "source",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.triageViewResponse"
                        }
                    },
                    "400": {
                        "description": "missing or invalid cluster_id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "missing or invalid admin token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "no such cluster",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/triage/bulk": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Uploads a client's whole local triage.State for one source and one cluster in a single call. Every field in each entry is authoritative (full replace, not a partial merge). Entries whose fingerprint has no matching Finding are skipped and reported, not treated as a hard failure.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "triage"
                ],
                "summary": "Bulk-replace triage entries for one source",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster ID",
                        "name": "cluster_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Source and its full set of triage entries",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.bulkTriageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.bulkTriageResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request body / missing source / missing or invalid cluster_id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "missing or invalid admin token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "no such cluster",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/triage/{source}/{fingerprint}": {
            "patch": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Partially updates the TriageEntry for one finding (source+fingerprint) of one cluster. Omitted fields keep their current value; a first update creates the entry with status \"new\" as the baseline.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "triage"
                ],
                "summary": "Update one triage entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster ID",
                        "name": "cluster_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ingest source, e.g. native or openreports",
                        "name": "source",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Finding fingerprint",
                        "name": "fingerprint",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server_http.patchTriageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ivanhahanov_kubectl-audit_internal_storage.TriageEntry"
                        }
                    },
                    "400": {
                        "description": "invalid request body / missing or invalid cluster_id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "missing or invalid admin token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "no such cluster / no such finding for this cluster/source/fingerprint",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_ivanhahanov_kubectl-audit_internal_storage.TriageEntry": {
            "type": "object",
            "properties": {
                "clusterID": {
                    "type": "string"
                },
                "fingerprint": {
                    "type": "string"
                },
                "jiraIssueKey": {
                    "type": "string"
                },
                "jiraIssueURL": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "reviewer": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_ivanhahanov_kubectl-audit_internal_storage.TriageStatus"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_ivanhahanov_kubectl-audit_internal_storage.TriageStatus": {
            "type": "string",
            "enum": [
                "new",
                "confirmed",
                "false_positive",
                "wont_fix",
                "duplicate",
                "needs_info",
                "resolved"
            ],
            "x-enum-varnames": [
                "TriageStatusNew",
                "TriageStatusConfirmed",
                "TriageStatusFalsePositive",
                "TriageStatusWontFix",
                "TriageStatusDuplicate",
                "TriageStatusNeedsInfo",
                "TriageStatusResolved"
            ]
        },
        "internal_server_http.auditRequestDTO": {
            "type": "object",
            "properties": {
                "clusterId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "requestedBy": {
                    "type": "string"
                },
                "scheduledCron": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tektonPipelineRunName": {
                    "type": "string"
                }
            }
        },
        "internal_server_http.automationActionDTO": {
            "type": "object",
            "properties": {
                "prompt": {
                    "type": "string"
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "internal_server_http.automationEvaluationResultDTO": {
            "type": "object",
            "properties": {
                "attempted": {
                    "type": "boolean"
                },
                "clusterId": {
                    "type": "string"
                },
                "detail": {
                    "type": "string"
                },
                "fingerprint": {
                    "type": "string"
                },
                "ruleId": {
                    "type": "string"
                },
                "ruleName": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "internal_server_http.automationRuleDTO": {
            "type": "object",
            "properties": {
                "action": {
                    "$ref": "#/definitions/internal_server_http.automationActionDTO"
                },
                "createdAt": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "trigger": {
                    "$ref": "#/definitions/internal_server_http.automationTriggerDTO"
                }
            }
        },
        "internal_server_http.automationTriggerDTO": {
            "type": "object",
            "properties": {
                "minSeverity": {
                    "type": "string"
                },
                "noJiraLinkForHours": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_server_http.bulkTriageEntry": {
            "type": "object",
            "properties": {
                "fingerprint": {
                    "type": "string"
                },
                "jiraIssueKey": {
                    "type": "string"
                },
                "jiraIssueUrl": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "reviewer": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_server_http.bulkTriageRequest": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_server_http.bulkTriageEntry"
                    }
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "internal_server_http.bulkTriageResponse": {
            "type": "object",
            "properties": {
                "skipped": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_server_http.bulkTriageSkip"
                    }
                },
                "updated": {
                    "type": "integer"
                }
            }
        },
        "internal_server_http.bulkTriageSkip": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "fingerprint": {
                    "type": "string"
                }
            }
        },
        "internal_server_http.exclusionMatchDTO": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                }
            }
        },
        "internal_server_http.exclusionRuleDTO": {
            "type": "object",
            "properties": {
                "clusterId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "match": {
                    "$ref": "#/definitions/internal_server_http.exclusionMatchDTO"
                },
                "policyIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "internal_server_http.ingestResponse": {
            "type": "object",
            "properties": {
                "scans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_server_http.scanResult"
                    }
                }
            }
        },
        "internal_server_http.knowledgeBaseEntryDTO": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "labels": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "policyId": {
                    "type": "string"
                },
                "remediation": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "internal_server_http.patchAuditRequestRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_server_http.patchTriageRequest": {
            "type": "object",
            "properties": {
                "jiraIssueKey": {
                    "type": "string"
                },
                "jiraIssueUrl": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "reviewer": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_server_http.registerClusterRequest": {
            "type": "object",
            "properties": {
                "endpoint": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                }
            }
        },
        "internal_server_http.registerClusterResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "internal_server_http.scanResult": {
            "type": "object",
            "properties": {
                "findingsIngested": {
                    "type": "integer"
                },
                "scanId": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "internal_server_http.triageResourceRef": {
            "type": "object",
            "properties": {
                "apiVersion": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                }
            }
        },
        "internal_server_http.triageView": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "fingerprint": {
                    "type": "string"
                },
                "firstSeen": {
                    "type": "string"
                },
                "jiraIssueKey": {
                    "type": "string"
                },
                "jiraIssueUrl": {
                    "type": "string"
                },
                "lastSeen": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "policyId": {
                    "type": "string"
                },
                "resource": {
                    "$ref": "#/definitions/internal_server_http.triageResourceRef"
                },
                "reviewer": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "internal_server_http.triageViewResponse": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_server_http.triageView"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "AdminAuth": {
            "description": "Admin bearer token (env ADMIN_TOKEN). Send as \"Bearer \u003ctoken\u003e\". Required for cluster registration and every organization-level config endpoint (knowledge base, exclusion rules, automation rules, audit requests).",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "ClusterAuth": {
            "description": "Per-cluster bearer token minted by POST /clusters. Send as \"Bearer \u003ctoken\u003e\". Required for ingest and triage endpoints; scopes access to that cluster's own data.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "kubectl-audit-server API",
	Description:      "Multi-cluster aggregation server for kubectl-audit: clusters push findings.json scans here, which are deduplicated and stored for cross-cluster triage, centralized knowledge base/exclusion rules, and automation rule evaluation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
