{{- if .Values.automation.tekton.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubectl-audit-server.fullname" . }}-tekton-trigger
  labels:
    {{- include "kubectl-audit-server.labels" . | nindent 4 }}
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubectl-audit-server.fullname" . }}-tekton-trigger
  labels:
    {{- include "kubectl-audit-server.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubectl-audit-server.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubectl-audit-server.fullname" . }}-tekton-trigger
  apiGroup: rbac.authorization.k8s.io
{{- end }}
