apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubectl-audit-server.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubectl-audit-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
