apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-audit-scan
  namespace: kubectl-audit-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectl-audit-scan
subjects:
  - kind: ServiceAccount
    name: kubectl-audit-scan
    namespace: kubectl-audit-system
roleRef:
  kind: ClusterRole
  name: kubectl-audit-readonly
  apiGroup: rbac.authorization.k8s.io
